root:
  path:     /
  defaults: { _controller: FrameworkBundle:Redirect:urlRedirect, path: /en, permanent: true }

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /{_locale}/profile

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /{_locale}/profile

list:
  path:     /{_locale}/{page}.{_format}
  defaults: { _controller: MailNotesBundle:List:List, _format: html, page: 1 }
  requirements:
      _locale:  en|de
      _format:  html|json
      page:     \d+

list_category:
  path:     /{_locale}/{categorySlug}/{page}.{_format}
  defaults: { _controller: MailNotesBundle:List:category, _format: html, page: 1 }
  requirements:
      _locale:  en|de
      _format:  html|json
      page:     \d+