va5ja\MailNotesBundle\Entity\Category:
    type: entity
    table: category
    uniqueConstraints:
        category_name:
            columns:
                - name
        category_slug:
            columns:
                - slug
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 64
            options:
                fixed: false
        slug:
            type: string
            nullable: true
            length: 64
            options:
                fixed: false
        datetime:
            type: datetime
            nullable: true
    lifecycleCallbacks: {  }
