AppBundle\Entity\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: true
            length: 25
            unique: true
            options:
                fixed: false
        password:
            type: string
            nullable: true
            length: 64
            options:
                fixed: false
        email:
            type: string
            nullable: true
            length: 60
            unique: true
            options:
                fixed: false
        isActive:
            type: boolean
            name: is_active
    lifecycleCallbacks: {  }
